// Mocks generated by Mockito 5.4.6 from annotations
// in broker_app/test/features/webview/presentation/pages/webview_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:broker_app/core/error/failures.dart' as _i6;
import 'package:broker_app/features/webview/domain/entities/platform_url.dart'
    as _i9;
import 'package:broker_app/features/webview/domain/repositories/webview_repository.dart'
    as _i2;
import 'package:broker_app/features/webview/domain/usecases/get_platform_url.dart'
    as _i8;
import 'package:broker_app/features/webview/domain/usecases/save_webview_state.dart'
    as _i7;
import 'package:broker_app/features/webview/domain/usecases/validate_url.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWebViewRepository_0 extends _i1.SmartFake
    implements _i2.WebViewRepository {
  _FakeWebViewRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ValidateUrl].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateUrl extends _i1.Mock implements _i4.ValidateUrl {
  MockValidateUrl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WebViewRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWebViewRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WebViewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
    _i4.ValidateUrlParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [SaveWebViewState].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWebViewState extends _i1.Mock implements _i7.SaveWebViewState {
  MockSaveWebViewState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WebViewRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWebViewRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WebViewRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i7.SaveWebViewStateParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetPlatformUrl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPlatformUrl extends _i1.Mock implements _i8.GetPlatformUrl {
  MockGetPlatformUrl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.PlatformUrl>> call(
    _i8.GetPlatformUrlParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i9.PlatformUrl>>.value(
                  _FakeEither_1<_i6.Failure, _i9.PlatformUrl>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i9.PlatformUrl>>);
}
