import 'package:supabase_flutter/supabase_flutter.dart';

import '../../../../core/error/exceptions.dart';
import '../../../cart/domain/entities/cart_item.dart';
import '../../domain/entities/shipping_method.dart';
import '../models/order_item_model.dart';
import '../models/order_model.dart';

/// Remote data source for order operations
abstract class OrderRemoteDataSource {
  /// Create new order from cart items
  Future<OrderModel> createOrder({
    required String userId,
    required List<CartItem> cartItems,
    required String addressId,
    required ShippingMethod shippingMethod,
  });

  /// Get all orders for user
  Future<List<OrderModel>> getUserOrders(String userId);

  /// Get order by ID
  Future<OrderModel> getOrderById(String orderId);

  /// Get order by reference number
  Future<OrderModel> getOrderByReference(String referenceNumber);

  /// Cancel order
  Future<void> cancelOrder(String orderId);
}

class OrderRemoteDataSourceImpl implements OrderRemoteDataSource {
  final SupabaseClient supabaseClient;

  OrderRemoteDataSourceImpl({required this.supabaseClient});

  @override
  Future<OrderModel> createOrder({
    required String userId,
    required List<CartItem> cartItems,
    required String addressId,
    required ShippingMethod shippingMethod,
  }) async {
    try {
      // Step 1: Get the address
      final addressResponse =
          await supabaseClient
              .from('user_addresses')
              .select()
              .eq('id', addressId)
              .single();

      // Step 2: Calculate total weight and price (both optional)
      double totalWeight = 0.01; // Minimum value to satisfy DB constraint
      double? totalPrice;
      List<double> weights = [];
      List<double> prices = [];

      for (var item in cartItems) {
        // Calculate weight if available
        if (item.weightKg != null) {
          weights.add(item.weightKg! * item.quantity);
        }

        // Try to calculate price
        final itemPrice = item.priceValue;
        if (itemPrice != null) {
          prices.add(itemPrice * item.quantity);
        }
      }

      // Set total weight (default to 0 if no weights available)
      totalWeight =
          weights.isNotEmpty
              ? weights.fold<double>(0.0, (sum, weight) => sum + weight)
              : 0.01; // Use 0.01 to satisfy DB constraint (total_weight_kg > 0)

      // Calculate total price if all items have valid prices
      if (prices.length == cartItems.length) {
        totalPrice = prices.fold<double>(0.0, (sum, price) => sum + price);
      }

      // Step 3: Create order
      // Note: Reference number will be auto-generated by trigger
      final orderData = {
        'user_id': userId,
        'shipping_address': addressResponse,
        'shipping_method': shippingMethod.toDbValue(),
        'total_weight_kg': totalWeight,
        'total_price': totalPrice,
        'currency': 'USD',
        'status': 'pending',
      };

      final orderResponse =
          await supabaseClient
              .from('orders')
              .insert(orderData)
              .select()
              .single();

      // Step 4: Create order items
      final orderId = orderResponse['id'] as String;
      final List<Map<String, dynamic>> itemsData = [];

      for (var item in cartItems) {
        // Use weightKg from CartItem entity, default to 0.01 if null
        final weightKg = item.weightKg ?? 0.01;
        itemsData.add({
          'order_id': orderId,
          'product_name': item.productName,
          'product_url': item.productUrl,
          'platform': item.platform,
          'price': item.price,
          'quantity': item.quantity,
          'weight_kg': weightKg,
          'image_url': item.imageUrl,
          'metadata': item.metadata,
        });
      }

      final itemsResponse =
          await supabaseClient.from('order_items').insert(itemsData).select();

      final orderItems =
          (itemsResponse as List<dynamic>)
              .map(
                (json) => OrderItemModel.fromJson(json as Map<String, dynamic>),
              )
              .toList();

      // Step 5: Return complete order with items
      return OrderModel.fromJsonWithItems(orderResponse, orderItems);
    } on PostgrestException catch (e) {
      throw ServerException(message: 'فشل إنشاء الطلب: ${e.message}');
    } on ServerException {
      rethrow;
    } catch (e) {
      throw ServerException(message: 'فشل إنشاء الطلب: ${e.toString()}');
    }
  }

  @override
  Future<List<OrderModel>> getUserOrders(String userId) async {
    try {
      // Get orders
      final ordersResponse = await supabaseClient
          .from('orders')
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      final List<OrderModel> orders = [];

      for (var orderJson in ordersResponse as List<dynamic>) {
        final orderId = orderJson['id'] as String;

        // Get items for this order
        final itemsResponse = await supabaseClient
            .from('order_items')
            .select()
            .eq('order_id', orderId)
            .order('created_at', ascending: false);

        final items =
            (itemsResponse as List<dynamic>)
                .map(
                  (json) =>
                      OrderItemModel.fromJson(json as Map<String, dynamic>),
                )
                .toList();

        orders.add(
          OrderModel.fromJsonWithItems(
            orderJson as Map<String, dynamic>,
            items,
          ),
        );
      }

      return orders;
    } on PostgrestException catch (e) {
      throw ServerException(message: 'فشل جلب الطلبات: ${e.message}');
    } catch (e) {
      throw ServerException(message: 'فشل جلب الطلبات: ${e.toString()}');
    }
  }

  @override
  Future<OrderModel> getOrderById(String orderId) async {
    try {
      // Get order
      final orderResponse =
          await supabaseClient
              .from('orders')
              .select()
              .eq('id', orderId)
              .single();

      // Get items
      final itemsResponse = await supabaseClient
          .from('order_items')
          .select()
          .eq('order_id', orderId)
          .order('created_at', ascending: false);

      final items =
          (itemsResponse as List<dynamic>)
              .map(
                (json) => OrderItemModel.fromJson(json as Map<String, dynamic>),
              )
              .toList();

      return OrderModel.fromJsonWithItems(orderResponse, items);
    } on PostgrestException catch (e) {
      throw ServerException(message: 'فشل جلب الطلب: ${e.message}');
    } catch (e) {
      throw ServerException(message: 'فشل جلب الطلب: ${e.toString()}');
    }
  }

  @override
  Future<OrderModel> getOrderByReference(String referenceNumber) async {
    try {
      // Get order
      final orderResponse =
          await supabaseClient
              .from('orders')
              .select()
              .eq('reference_number', referenceNumber)
              .single();

      final orderId = orderResponse['id'] as String;

      // Get items
      final itemsResponse = await supabaseClient
          .from('order_items')
          .select()
          .eq('order_id', orderId)
          .order('created_at', ascending: false);

      final items =
          (itemsResponse as List<dynamic>)
              .map(
                (json) => OrderItemModel.fromJson(json as Map<String, dynamic>),
              )
              .toList();

      return OrderModel.fromJsonWithItems(orderResponse, items);
    } on PostgrestException catch (e) {
      throw ServerException(message: 'فشل جلب الطلب: ${e.message}');
    } catch (e) {
      throw ServerException(message: 'فشل جلب الطلب: ${e.toString()}');
    }
  }

  @override
  Future<void> cancelOrder(String orderId) async {
    try {
      // Check if order can be cancelled (status should be pending or processing)
      final orderResponse =
          await supabaseClient
              .from('orders')
              .select('status')
              .eq('id', orderId)
              .single();

      final status = orderResponse['status'] as String;
      if (status != 'pending' && status != 'processing') {
        throw ServerException(message: 'لا يمكن إلغاء هذا الطلب');
      }

      // Update order status to cancelled
      await supabaseClient
          .from('orders')
          .update({
            'status': 'cancelled',
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', orderId);
    } on PostgrestException catch (e) {
      throw ServerException(message: 'فشل إلغاء الطلب: ${e.message}');
    } on ServerException {
      rethrow;
    } catch (e) {
      throw ServerException(message: 'فشل إلغاء الطلب: ${e.toString()}');
    }
  }
}
